import type { ChartTheme, ChartThemeId } from '../types'

export const CHART_THEMES: Record<ChartThemeId, ChartTheme> = {
  'dark-terminal': {
    id:             'dark-terminal',
    name:           'Dark Terminal',
    bg:             '#0a0c0f',
    bgSecondary:    '#0d1117',
    grid:           '#131821',
    gridOpacity:    1,
    text:           '#c8cdd6',
    textMuted:      '#5a6373',
    upColor:        '#22c55e',
    upBody:         '#1a7a4a',
    upWick:         '#22c55e',
    downColor:      '#ef4444',
    downBody:       '#7a1a1a',
    downWick:       '#ef4444',
    crosshair:      '#f0b429',
    crosshairLabel: '#0a0c0f',
    volumeUp:       'rgba(34,197,94,0.25)',
    volumeDown:     'rgba(239,68,68,0.25)',
    axisText:       '#5a6373',
    borderColor:    '#1e2530',
  },
  'dark-pro': {
    id:             'dark-pro',
    name:           'Dark Pro',
    bg:             '#131722',
    bgSecondary:    '#1c2030',
    grid:           '#1e2a3a',
    gridOpacity:    1,
    text:           '#d1d4dc',
    textMuted:      '#636d7e',
    upColor:        '#26a69a',
    upBody:         '#26a69a',
    upWick:         '#26a69a',
    downColor:      '#ef5350',
    downBody:       '#ef5350',
    downWick:       '#ef5350',
    crosshair:      '#9598a1',
    crosshairLabel: '#131722',
    volumeUp:       'rgba(38,166,154,0.3)',
    volumeDown:     'rgba(239,83,80,0.3)',
    axisText:       '#636d7e',
    borderColor:    '#2a2e39',
  },
  'light-clean': {
    id:             'light-clean',
    name:           'Light Clean',
    bg:             '#ffffff',
    bgSecondary:    '#f5f5f5',
    grid:           '#e6e6e6',
    gridOpacity:    1,
    text:           '#131722',
    textMuted:      '#787b86',
    upColor:        '#26a69a',
    upBody:         '#26a69a',
    upWick:         '#26a69a',
    downColor:      '#ef5350',
    downBody:       '#ef5350',
    downWick:       '#ef5350',
    crosshair:      '#9598a1',
    crosshairLabel: '#ffffff',
    volumeUp:       'rgba(38,166,154,0.3)',
    volumeDown:     'rgba(239,83,80,0.3)',
    axisText:       '#787b86',
    borderColor:    '#cccccc',
  },
  'bloomberg': {
    id:             'bloomberg',
    name:           'Bloomberg',
    bg:             '#000000',
    bgSecondary:    '#0a0a0a',
    grid:           '#1a1a1a',
    gridOpacity:    1,
    text:           '#ff9900',
    textMuted:      '#664400',
    upColor:        '#ff9900',
    upBody:         '#ff6600',
    upWick:         '#ff9900',
    downColor:      '#cc3300',
    downBody:       '#cc3300',
    downWick:       '#cc3300',
    crosshair:      '#ff9900',
    crosshairLabel: '#000000',
    volumeUp:       'rgba(255,153,0,0.3)',
    volumeDown:     'rgba(204,51,0,0.3)',
    axisText:       '#664400',
    borderColor:    '#333300',
  },
}

// Convert ChartTheme to KlineCharts styles object
export function themeToKlineStyles(theme: ChartTheme) {
  return {
    grid: {
      show: true,
      horizontal: { show: true, size: 1, color: theme.grid, style: 'dashed', dashValue: [2, 2] },
      vertical:   { show: true, size: 1, color: theme.grid, style: 'dashed', dashValue: [2, 2] },
    },
    candle: {
      type: 'candle_solid',
      bar: {
        upColor:          theme.upBody,
        downColor:        theme.downBody,
        noChangeColor:    '#888888',
        upBorderColor:    theme.upColor,
        downBorderColor:  theme.downColor,
        noChangeBorderColor: '#888888',
        upWickColor:      theme.upWick,
        downWickColor:    theme.downWick,
        noChangeWickColor: '#888888',
      },
      priceMark: {
        show: true,
        high: { show: true, color: theme.text, textOffset: 5, textSize: 10, textFamily: "'Courier New', monospace", textWeight: 'normal' },
        low:  { show: true, color: theme.text, textOffset: 5, textSize: 10, textFamily: "'Courier New', monospace", textWeight: 'normal' },
        last: {
          show: true,
          upColor: theme.upColor, downColor: theme.downColor, noChangeColor: '#888888',
          line: { show: true, style: 'dashed', dashValue: [4, 3], size: 1 },
          text: {
            show: true, style: 'fill', size: 10,
            paddingLeft: 3, paddingTop: 2, paddingRight: 3, paddingBottom: 2,
            borderRadius: 2, color: theme.crosshairLabel,
            family: "'Courier New', monospace", weight: 'bold',
          },
        },
      },
      tooltip: {
        showRule: 'always', showType: 'rect',
        rect: { paddingLeft: 8, paddingRight: 8, paddingTop: 4, paddingBottom: 6, offsetLeft: 8, offsetTop: 8, borderRadius: 4, borderSize: 1, borderColor: theme.borderColor, color: theme.bgSecondary },
        text: { size: 10, family: "'Courier New', monospace", weight: 'normal', color: theme.text, marginLeft: 8, marginTop: 4, marginRight: 8, marginBottom: 0 },
      },
    },
    indicator: {
      ohlc: { upColor: theme.upColor, downColor: theme.downColor, noChangeColor: '#888888' },
      bars: [
        { style: 'fill', borderStyle: 'solid', borderSize: 1, borderDashedValue: [2, 2], upColor: theme.upColor, downColor: theme.downColor, noChangeColor: '#888888' }
      ],
      lines: [
        { style: 'solid', smooth: false, size: 1, dashValue: [2, 2], color: '#f0b429' },
        { style: 'solid', smooth: false, size: 1, dashValue: [2, 2], color: '#378add' },
        { style: 'solid', smooth: false, size: 1, dashValue: [2, 2], color: '#22c55e' },
        { style: 'solid', smooth: false, size: 1, dashValue: [2, 2], color: '#ef4444' },
        { style: 'solid', smooth: false, size: 1, dashValue: [2, 2], color: '#7f77dd' },
      ],
      tooltip: {
        showRule: 'always', showType: 'rect',
        rect: { paddingLeft: 8, paddingRight: 8, paddingTop: 4, paddingBottom: 6, offsetLeft: 8, offsetTop: 8, borderRadius: 4, borderSize: 1, borderColor: theme.borderColor, color: theme.bgSecondary },
        text: { size: 10, family: "'Courier New', monospace", weight: 'normal', color: theme.text, marginLeft: 8, marginTop: 4, marginRight: 8, marginBottom: 0 },
      },
    },
    xAxis: {
      show: true,
      size: 22,
      axisLine: { show: true, color: theme.borderColor, size: 1 },
      tickText: { show: true, color: theme.axisText, family: "'Courier New', monospace", weight: 'normal', size: 10 },
      tickLine: { show: true, size: 1, length: 3, color: theme.borderColor },
    },
    yAxis: {
      show: true,
      size: 60,
      axisLine: { show: true, color: theme.borderColor, size: 1 },
      tickText: { show: true, color: theme.axisText, family: "'Courier New', monospace", weight: 'normal', size: 10 },
      tickLine: { show: true, size: 1, length: 3, color: theme.borderColor },
    },
    separator: {
      size: 1, color: theme.borderColor, fill: true,
      activeBackgroundColor: `${theme.borderColor}40`,
    },
    crosshair: {
      show: true,
      horizontal: {
        show: true, line: { show: true, style: 'dashed', dashValue: [4, 2], size: 1, color: theme.crosshair },
        text: { show: true, style: 'fill', color: theme.crosshairLabel, size: 10, family: "'Courier New', monospace", weight: 'bold', paddingLeft: 4, paddingRight: 4, paddingTop: 2, paddingBottom: 2, borderRadius: 2 },
      },
      vertical: {
        show: true, line: { show: true, style: 'dashed', dashValue: [4, 2], size: 1, color: theme.crosshair },
        text: { show: true, style: 'fill', color: theme.crosshairLabel, size: 10, family: "'Courier New', monospace", weight: 'bold', paddingLeft: 4, paddingRight: 4, paddingTop: 2, paddingBottom: 2, borderRadius: 2 },
      },
    },
    overlay: {
      point: { color: theme.crosshair, borderColor: theme.crosshairLabel, borderSize: 1, radius: 5, activeColor: theme.crosshair, activeBorderColor: theme.crosshairLabel, activeBorderSize: 1, activeRadius: 7 },
      line: { style: 'solid', smooth: false, color: theme.crosshair, size: 1, dashValue: [2, 2] },
      rect: { style: 'stroke_fill', color: `${theme.crosshair}20`, borderColor: theme.crosshair, borderSize: 1, borderStyle: 'solid', borderDashedValue: [2, 2], borderRadius: 0 },
      polygon: { style: 'stroke_fill', color: `${theme.crosshair}20`, borderColor: theme.crosshair, borderSize: 1, borderStyle: 'solid', borderDashedValue: [2, 2] },
      circle: { style: 'stroke_fill', color: `${theme.crosshair}20`, borderColor: theme.crosshair, borderSize: 1, borderStyle: 'solid', borderDashedValue: [2, 2] },
      arc:    { style: 'solid', color: theme.crosshair, size: 1 },
      text:   { style: 'fill', color: theme.text, size: 12, family: "'Courier New', monospace", weight: 'normal', paddingLeft: 2, paddingRight: 2, paddingTop: 2, paddingBottom: 2, borderRadius: 2, borderSize: 0, borderColor: theme.borderColor, backgroundColor: theme.bgSecondary },
    },
  }
}
